services:
  mcp-bridge:
    build:
      context: ./docker
      additional_contexts:
         requirements: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: mcp_bridge
          action: rebuild
    container_name: mcp-bridge2
    ports:
      - "8000:8000"
    environment:
      - MCP_BRIDGE__CONFIG__FILE=config.json # mount the config file for this to work
      # - MCP_BRIDGE__CONFIG__HTTP_URL=http://10.88.100.170:8888/config.json
      # - MCP_BRIDGE__CONFIG__JSON=
    # volumes:
    #   - ./config.json:/mcp_bridge/config.json
    volumes:
      - ./docker/config.json.template:/mcp_bridge/config.json.template
    restart: unless-stopped
    env_file: ./creds.env
